sudo: required

language: c

services:
    - docker

install: true

script:
    - make build

after_success:
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - make push

