FROM scratch
MAINTAINER Arun Neelicattu <arun.neelicattu@gmail.com>

ADD ./bin/consul /consul
ADD ./rootfs/lib64 /lib64
ADD ./rootfs/data /data

VOLUME /data
EXPOSE \
    53/tcp 53/udp \
    8300/tcp \
    8301/tcp 8301/udp \
    8302/tcp 8302/udp \
    8400/tcp \
    8500/tcp \
    8600/tcp 8600/udp

ENTRYPOINT ["/consul"]
CMD ["agent", "-server", "-bootstrap-expect", "1","-data-dir", "/data"]
