FROM scratch
MAINTAINER Arun Neelicattu <arun.neelicattu@gmail.com>

COPY ./rootfs /

VOLUME ["/etc/consul", "/var/lib/consul", "/usr/share/consul-ui"]

EXPOSE \
    53/tcp 53/udp \
    8300/tcp \
    8301/tcp 8301/udp \
    8302/tcp 8302/udp \
    8400/tcp \
    8500/tcp \
    8600/tcp 8600/udp

ENTRYPOINT ["/usr/bin/consul", \
    "agent", \
    "-config-dir=/etc/consul", \
    "-data-dir=/var/lib/consul"]

CMD ["-server", "-bootstrap", "-client=0.0.0.0", "-ui-dir=/usr/share/consul-ui"]
